In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

D:\Jul_12_2025\MLPracticeEnv\tfenv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [2]:
df = pd.read_csv(r'D:\Jul_12_2025\DS_Datasets\Exam_Score_Prediction.csv')
df

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19997,18,other,bba,6.50,71.3,yes,5.0,good,self-study,low,easy,86.5
19996,19998,18,male,b.com,3.71,41.6,no,5.9,average,coaching,medium,moderate,60.9
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [3]:
df.drop(columns = ['student_id'], inplace = True)
x = df.drop(columns = ['exam_score'])
y = df.exam_score
encoded = pd.get_dummies(x, dtype = int)
encoded

,age,study_hours,class_attendance,sleep_hours,gender_female,gender_male,gender_other,course_b.com,course_b.sc,course_b.tech,...,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,facility_rating_high,facility_rating_low,facility_rating_medium,exam_difficulty_easy,exam_difficulty_hard,exam_difficulty_moderate
0,17,2.78,92.9,7.4,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
1,23,3.37,64.8,4.6,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,1
2,22,7.88,76.8,8.5,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
3,20,0.67,48.4,5.8,0,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,1
4,20,0.89,71.6,9.8,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,18,6.50,71.3,5.0,0,0,1,0,0,0,...,0,0,0,1,0,1,0,1,0,0
19996,18,3.71,41.6,5.9,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
19997,19,7.88,68.2,4.6,0,0,1,0,0,0,...,1,0,0,0,0,1,0,1,0,0
19998,19,4.60,76.3,6.1,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
19999,20,7.50,47.9,7.5,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1

In [15]:
import pickle
feature_names = encoded.columns.tolist()
with open("feature_names.pkl", "wb") as f:
    pickle.dump(feature_names, f)

In [4]:
x_train,x_test,y_train,y_test = train_test_split(encoded, y,test_size=0.2, random_state=10)

In [11]:
model = Sequential()

model.add(Dense(units=8, activation='relu', input_dim=30))
model.add(Dense(units=4, activation='relu'))
model.add(Dense(units=1, activation='linear'))

model.compile(optimizer='adam', metrics=['r2_score'], loss='mean_squared_error')
history = model.fit(x_train, y_train, epochs=100, validation_split=0.2, batch_size=64,verbose=2)

D:\Jul_12_2025\MLPracticeEnv\tfenv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
200/200 - 2s - 11ms/step - loss: 1100.2576 - r2_score: -2.0387e+00 - val_loss: 345.9719 - val_r2_score: 0.0068
Epoch 2/100
200/200 - 1s - 3ms/step - loss: 331.1059 - r2_score: 0.0855 - val_loss: 329.7154 - val_r2_score: 0.0534
Epoch 3/100
200/200 - 1s - 3ms/step - loss: 314.3257 - r2_score: 0.1319 - val_loss: 310.8940 - val_r2_score: 0.1075
Epoch 4/100
200/200 - 1s - 3ms/step - loss: 295.5502 - r2_score: 0.1837 - val_loss: 290.1231 - val_r2_score: 0.1671
Epoch 5/100
200/200 - 1s - 3ms/step - loss: 274.8891 - r2_score: 0.2408 - val_loss: 267.3307 - val_r2_score: 0.2325
Epoch 6/100
200/200 - 1s - 3ms/step - loss: 252.1825 - r2_score: 0.3035 - val_loss: 241.9215 - val_r2_score: 0.3055
Epoch 7/100
200/200 - 1s - 3ms/step - loss: 225.4922 - r2_score: 0.3772 - val_loss: 204.9233 - val_r2_score: 0.4117
Epoch 8/100
200/200 - 1s - 3ms/step - loss: 185.0180 - r2_score: 0.4890 - val_loss: 164.7789 - val_r2_score: 0.5269
Epoch 9/100
200/200 - 1s - 3ms/step - loss: 150.3766 - r2_score: 0.5847 - val_loss: 132.9651 - val_r2_score: 0.6183
Epoch 10/100
200/200 - 1s - 3ms/step - loss: 125.0351 - r2_score: 0.6547 - val_loss: 113.6203 - val_r2_score: 0.6738
Epoch 11/100
200/200 - 1s - 3ms/step - loss: 109.6834 - r2_score: 0.6971 - val_loss: 102.0687 - val_r2_score: 0.7070
Epoch 12/100
200/200 - 1s - 3ms/step - loss: 101.6466 - r2_score: 0.7193 - val_loss: 97.2563 - val_r2_score: 0.7208
Epoch 13/100
200/200 - 1s - 3ms/step - loss: 98.0953 - r2_score: 0.7291 - val_loss: 95.9111 - val_r2_score: 0.7247
Epoch 14/100
200/200 - 1s - 3ms/step - loss: 96.6338 - r2_score: 0.7331 - val_loss: 94.9771 - val_r2_score: 0.7273
Epoch 15/100
200/200 - 1s - 3ms/step - loss: 96.1408 - r2_score: 0.7345 - val_loss: 94.5987 - val_r2_score: 0.7284
Epoch 16/100
200/200 - 1s - 3ms/step - loss: 95.8196 - r2_score: 0.7354 - val_loss: 94.4917 - val_r2_score: 0.7287
Epoch 17/100
200/200 - 1s - 3ms/step - loss: 95.5250 - r2_score: 0.7362 - val_loss: 94.6065 - val_r2_score: 0.7284
Epoch 18/100
200/200 - 1s - 3ms/step - loss: 95.6137 - r2_score: 0.7359 - val_loss: 94.3984 - val_r2_score: 0.7290
Epoch 19/100
200/200 - 1s - 3ms/step - loss: 95.3609 - r2_score: 0.7366 - val_loss: 96.4121 - val_r2_score: 0.7232
Epoch 20/100
200/200 - 1s - 4ms/step - loss: 95.5081 - r2_score: 0.7362 - val_loss: 94.6229 - val_r2_score: 0.7284
Epoch 21/100
200/200 - 1s - 3ms/step - loss: 95.4802 - r2_score: 0.7363 - val_loss: 95.8745 - val_r2_score: 0.7248
Epoch 22/100
200/200 - 1s - 3ms/step - loss: 95.3939 - r2_score: 0.7365 - val_loss: 94.4394 - val_r2_score: 0.7289
Epoch 23/100
200/200 - 1s - 3ms/step - loss: 95.3769 - r2_score: 0.7366 - val_loss: 94.6455 - val_r2_score: 0.7283
Epoch 24/100
200/200 - 1s - 3ms/step - loss: 95.2420 - r2_score: 0.7370 - val_loss: 94.7975 - val_r2_score: 0.7279
Epoch 25/100
200/200 - 1s - 4ms/step - loss: 95.4041 - r2_score: 0.7365 - val_loss: 95.2352 - val_r2_score: 0.7266
Epoch 26/100
200/200 - 1s - 3ms/step - loss: 95.3765 - r2_score: 0.7366 - val_loss: 94.4537 - val_r2_score: 0.7288
Epoch 27/100
200/200 - 1s - 3ms/step - loss: 95.4221 - r2_score: 0.7365 - val_loss: 95.0605 - val_r2_score: 0.7271
Epoch 28/100
200/200 - 1s - 3ms/step - loss: 95.2935 - r2_score: 0.7368 - val_loss: 94.6468 - val_r2_score: 0.7283
Epoch 29/100
200/200 - 1s - 3ms/step - loss: 95.6049 - r2_score: 0.7360 - val_loss: 95.0685 - val_r2_score: 0.7271
Epoch 30/100
200/200 - 1s - 3ms/step - loss: 95.3270 - r2_score: 0.7367 - val_loss: 94.4762 - val_r2_score: 0.7288
Epoch 31/100
200/200 - 1s - 3ms/step - loss: 95.1277 - r2_score: 0.7373 - val_loss: 94.4067 - val_r2_score: 0.7290
Epoch 32/100
200/200 - 1s - 4ms/step - loss: 95.5840 - r2_score: 0.7360 - val_loss: 95.0913 - val_r2_score: 0.7270
Epoch 33/100
200/200 - 1s - 3ms/step - loss: 95.3069 - r2_score: 0.7368 - val_loss: 94.7770 - val_r2_score: 0.7279
Epoch 34/100
200/200 - 1s - 3ms/step - loss: 95.2517 - r2_score: 0.7369 - val_loss: 94.4197 - val_r2_score: 0.7289
Epoch 35/100
200/200 - 1s - 3ms/step - loss: 95.3062 - r2_score: 0.7368 - val_loss: 97.1559 - val_r2_score: 0.7211
Epoch 36/100
200/200 - 1s - 3ms/step - loss: 95.4735 - r2_score: 0.7363 - val_loss: 95.0806 - val_r2_score: 0.7270
Epoch 37/100
200/200 - 1s - 4ms/step - loss: 95.3050 - r2_score: 0.7368 - val_loss: 94.5237 - val_r2_score: 0.7286
Epoch 38/100
200/200 - 1s - 3ms/step - loss: 95.3984 - r2_score: 0.7365 - val_loss: 94.4133 - val_r2_score: 0.7290
Epoch 39/100
200/200 - 1s - 3ms/step - loss: 95.2764 - r2_score: 0.7369 - val_loss: 94.4321 - val_r2_score: 0.7289
Epoch 40/100
200/200 - 1s - 3ms/step - loss: 95.3266 - r2_score: 0.7367 - val_loss: 94.5859 - val_r2_score: 0.7285
Epoch 41/100
200/200 - 1s - 3ms/step - loss: 95.3713 - r2_score: 0.7366 - val_loss: 94.7236 - val_r2_score: 0.7281
Epoch 42/100
200/200 - 1s - 3ms/step - loss: 95.5058 - r2_score: 0.7362 - val_loss: 96.1304 - val_r2_score: 0.7240
Epoch 43/100
200/200 - 1s - 3ms/step - loss: 95.5108 - r2_score: 0.7362 - val_loss: 94.7738 - val_r2_score: 0.7279
Epoch 44/100
200/200 - 1s - 3ms/step - loss: 95.1451 - r2_score: 0.7372 - val_loss: 94.4712 - val_r2_score: 0.7288
Epoch 45/100
200/200 - 1s - 3ms/step - loss: 95.2063 - r2_score: 0.7371 - val_loss: 94.6256 - val_r2_score: 0.7283
Epoch 46/100
200/200 - 1s - 3ms/step - loss: 95.6078 - r2_score: 0.7359 - val_loss: 96.3108 - val_r2_score: 0.7235
Epoch 47/100
200/200 - 1s - 3ms/step - loss: 95.4637 - r2_score: 0.7363 - val_loss: 94.5128 - val_r2_score: 0.7287
Epoch 48/100
200/200 - 1s - 3ms/step - loss: 95.2144 - r2_score: 0.7370 - val_loss: 94.4985 - val_r2_score: 0.7287
Epoch 49/100
200/200 - 1s - 3ms/step - loss: 95.3702 - r2_score: 0.7366 - val_loss: 94.4901 - val_r2_score: 0.7287
Epoch 50/100
200/200 - 1s - 3ms/step - loss: 95.3846 - r2_score: 0.7366 - val_loss: 94.8111 - val_r2_score: 0.7278
Epoch 51/100
200/200 - 1s - 3ms/step - loss: 95.2213 - r2_score: 0.7370 - val_loss: 94.4638 - val_r2_score: 0.7288
Epoch 52/100
200/200 - 1s - 3ms/step - loss: 95.2218 - r2_score: 0.7370 - val_loss: 95.5763 - val_r2_score: 0.7256
Epoch 53/100
200/200 - 1s - 3ms/step - loss: 95.5094 - r2_score: 0.7362 - val_loss: 94.8028 - val_r2_score: 0.7278
Epoch 54/100
200/200 - 1s - 3ms/step - loss: 95.0800 - r2_score: 0.7374 - val_loss: 94.4283 - val_r2_score: 0.7289
Epoch 55/100
200/200 - 1s - 3ms/step - loss: 95.3079 - r2_score: 0.7368 - val_loss: 94.4543 - val_r2_score: 0.7288
Epoch 56/100
200/200 - 1s - 3ms/step - loss: 95.2911 - r2_score: 0.7368 - val_loss: 94.7125 - val_r2_score: 0.7281
Epoch 57/100
200/200 - 1s - 3ms/step - loss: 95.1322 - r2_score: 0.7373 - val_loss: 94.5022 - val_r2_score: 0.7287
Epoch 58/100
200/200 - 1s - 3ms/step - loss: 95.1305 - r2_score: 0.7373 - val_loss: 95.2676 - val_r2_score: 0.7265
Epoch 59/100
200/200 - 1s - 3ms/step - loss: 95.6967 - r2_score: 0.7357 - val_loss: 98.8689 - val_r2_score: 0.7162
Epoch 60/100
200/200 - 1s - 3ms/step - loss: 95.3054 - r2_score: 0.7368 - val_loss: 94.4048 - val_r2_score: 0.7290
Epoch 61/100
200/200 - 1s - 3ms/step - loss: 95.3007 - r2_score: 0.7368 - val_loss: 94.7773 - val_r2_score: 0.7279
Epoch 62/100
200/200 - 1s - 3ms/step - loss: 95.1045 - r2_score: 0.7373 - val_loss: 95.2935 - val_r2_score: 0.7264
Epoch 63/100
200/200 - 1s - 3ms/step - loss: 95.2339 - r2_score: 0.7370 - val_loss: 94.4147 - val_r2_score: 0.7290
Epoch 64/100
200/200 - 1s - 3ms/step - loss: 94.9373 - r2_score: 0.7378 - val_loss: 95.5197 - val_r2_score: 0.7258
Epoch 65/100
200/200 - 1s - 4ms/step - loss: 95.2499 - r2_score: 0.7369 - val_loss: 95.2415 - val_r2_score: 0.7266
Epoch 66/100
200/200 - 1s - 4ms/step - loss: 95.5493 - r2_score: 0.7361 - val_loss: 94.8692 - val_r2_score: 0.7276
Epoch 67/100
200/200 - 1s - 4ms/step - loss: 95.3900 - r2_score: 0.7365 - val_loss: 94.7618 - val_r2_score: 0.7280
Epoch 68/100
200/200 - 1s - 3ms/step - loss: 95.3121 - r2_score: 0.7368 - val_loss: 94.4665 - val_r2_score: 0.7288
Epoch 69/100
200/200 - 1s - 3ms/step - loss: 95.1804 - r2_score: 0.7371 - val_loss: 94.8454 - val_r2_score: 0.7277
Epoch 70/100
200/200 - 1s - 3ms/step - loss: 95.1228 - r2_score: 0.7373 - val_loss: 95.1475 - val_r2_score: 0.7268
Epoch 71/100
200/200 - 1s - 3ms/step - loss: 95.3413 - r2_score: 0.7367 - val_loss: 94.5286 - val_r2_score: 0.7286
Epoch 72/100
200/200 - 1s - 3ms/step - loss: 95.2599 - r2_score: 0.7369 - val_loss: 94.5305 - val_r2_score: 0.7286
Epoch 73/100
200/200 - 1s - 3ms/step - loss: 95.4585 - r2_score: 0.7364 - val_loss: 94.5371 - val_r2_score: 0.7286
Epoch 74/100
200/200 - 1s - 3ms/step - loss: 95.2165 - r2_score: 0.7370 - val_loss: 95.1366 - val_r2_score: 0.7269
Epoch 75/100
200/200 - 1s - 3ms/step - loss: 95.2242 - r2_score: 0.7370 - val_loss: 94.6027 - val_r2_score: 0.7284
Epoch 76/100
200/200 - 1s - 4ms/step - loss: 95.2901 - r2_score: 0.7368 - val_loss: 94.5858 - val_r2_score: 0.7285
Epoch 77/100
200/200 - 1s - 3ms/step - loss: 95.2007 - r2_score: 0.7371 - val_loss: 95.4632 - val_r2_score: 0.7259
Epoch 78/100
200/200 - 1s - 3ms/step - loss: 95.0208 - r2_score: 0.7376 - val_loss: 95.3793 - val_r2_score: 0.7262
Epoch 79/100
200/200 - 1s - 4ms/step - loss: 95.1917 - r2_score: 0.7371 - val_loss: 94.5451 - val_r2_score: 0.7286
Epoch 80/100
200/200 - 1s - 3ms/step - loss: 95.3489 - r2_score: 0.7367 - val_loss: 94.4881 - val_r2_score: 0.7287
Epoch 81/100
200/200 - 1s - 4ms/step - loss: 95.4022 - r2_score: 0.7365 - val_loss: 95.4360 - val_r2_score: 0.7260
Epoch 82/100
200/200 - 1s - 3ms/step - loss: 95.3567 - r2_score: 0.7366 - val_loss: 94.4353 - val_r2_score: 0.7289
Epoch 83/100
200/200 - 1s - 4ms/step - loss: 95.3496 - r2_score: 0.7367 - val_loss: 94.6390 - val_r2_score: 0.7283
Epoch 84/100
200/200 - 1s - 5ms/step - loss: 95.1994 - r2_score: 0.7371 - val_loss: 94.4369 - val_r2_score: 0.7289
Epoch 85/100
200/200 - 1s - 3ms/step - loss: 95.2735 - r2_score: 0.7369 - val_loss: 94.6723 - val_r2_score: 0.7282
Epoch 86/100
200/200 - 1s - 3ms/step - loss: 95.1155 - r2_score: 0.7373 - val_loss: 94.9658 - val_r2_score: 0.7274
Epoch 87/100
200/200 - 1s - 3ms/step - loss: 95.4192 - r2_score: 0.7365 - val_loss: 95.3878 - val_r2_score: 0.7262
Epoch 88/100
200/200 - 1s - 3ms/step - loss: 95.2344 - r2_score: 0.7370 - val_loss: 94.4842 - val_r2_score: 0.7288
Epoch 89/100
200/200 - 1s - 3ms/step - loss: 95.1699 - r2_score: 0.7372 - val_loss: 94.4837 - val_r2_score: 0.7288
Epoch 90/100
200/200 - 1s - 3ms/step - loss: 95.2324 - r2_score: 0.7370 - val_loss: 95.1798 - val_r2_score: 0.7268
Epoch 91/100
200/200 - 1s - 3ms/step - loss: 95.1852 - r2_score: 0.7371 - val_loss: 94.5417 - val_r2_score: 0.7286
Epoch 92/100
200/200 - 1s - 3ms/step - loss: 95.1846 - r2_score: 0.7371 - val_loss: 94.4690 - val_r2_score: 0.7288
Epoch 93/100
200/200 - 1s - 3ms/step - loss: 95.1404 - r2_score: 0.7372 - val_loss: 94.5046 - val_r2_score: 0.7287
Epoch 94/100
200/200 - 1s - 3ms/step - loss: 95.2814 - r2_score: 0.7368 - val_loss: 94.5763 - val_r2_score: 0.7285
Epoch 95/100
200/200 - 1s - 3ms/step - loss: 95.3699 - r2_score: 0.7366 - val_loss: 94.7898 - val_r2_score: 0.7279
Epoch 96/100
200/200 - 1s - 3ms/step - loss: 95.3887 - r2_score: 0.7366 - val_loss: 95.8064 - val_r2_score: 0.7250
Epoch 97/100
200/200 - 1s - 3ms/step - loss: 95.2239 - r2_score: 0.7370 - val_loss: 94.5006 - val_r2_score: 0.7287
Epoch 98/100
200/200 - 1s - 4ms/step - loss: 95.3546 - r2_score: 0.7366 - val_loss: 94.5316 - val_r2_score: 0.7286
Epoch 99/100
200/200 - 1s - 3ms/step - loss: 95.3414 - r2_score: 0.7367 - val_loss: 94.9192 - val_r2_score: 0.7275
Epoch 100/100
200/200 - 1s - 3ms/step - loss: 95.3273 - r2_score: 0.7367 - val_loss: 94.6135 - val_r2_score: 0.7284

In [12]:
y_train_pred = model.predict(x_train)

mse = mean_squared_error(y_train, y_train_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_train, y_train_pred)
print("MAE : ", mae)
accuracy = r2_score(y_train, y_train_pred)
print("R2_Score", accuracy)

500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
MSE :  94.98770763103869
MAE :  7.832132427853584
R2_Score 0.7356524736559396

In [16]:
y_test_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_test_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_test, y_test_pred)
print("MAE : ", mae)
accuracy = r2_score(y_test, y_test_pred)
print("R2_Score", accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
MSE :  100.60088930849838
MAE :  8.029927461559296
R2_Score 0.7125998023524693

In [17]:
model.save('AnnExamScoreModel.keras')

In [21]:
model.save('AnnExamScoreModel.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

### Test User input

In [5]:
from tensorflow.keras.models import load_model

In [6]:
model = load_model('AnnExamScoreModel.keras')

In [12]:
model.input_shape[1]

30

In [39]:
model.get_config()

{'name': 'sequential_2',
 'trainable': True,
 'dtype': {'module': 'keras',
  'class_name': 'DTypePolicy',
  'config': {'name': 'float32'},
  'registered_name': None},
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_shape': (None, 30),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'input_layer_1',
    'optional': False},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_4',
    'trainable': True,
    'dtype': {'module': 'keras',
     'class_name': 'DTypePolicy',
     'config': {'name': 'float32'},
     'registered_name': None},
    'units': 8,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None,
    'quantization_config': None},
   'registered_name': None,
   'build_config': {'input_shape': [None, 30]}},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_5',
    'trainable': True,
    'dtype': {'module': 'keras',
     'class_name': 'DTypePolicy',
     'config': {'name': 'float32'},
     'registered_name': None},
    'units': 4,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None,
    'quantization_config': None},
   'registered_name': None,
   'build_config': {'input_shape': [None, 8]}},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_6',
    'trainable': True,
    'dtype': {'module': 'keras',
     'class_name': 'DTypePolicy',
     'config': {'name': 'float32'},
     'registered_name': None},
    'units': 1,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None,
    'quantization_config': None},
   'registered_name': None,
   'build_config': {'input_shape': [None, 4]}}],
 'build_input_shape': (None, 30)}